#!/bin/bash

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
readonly ROOT_DIR

cd "$ROOT_DIR"

echo '[pre-push] Running npm run all'
npm run all

echo '[pre-push] Running scripts/super-linter/run-super-linter.sh'
bash scripts/super-linter/run-super-linter.sh lint-changed
