# Issue PR Labeler
# https://github.com/hoho4190/issue-pr-labeler

settings:
  skipIfBot: false
  removeUnmatchedLabels: true
  onMissingLabel: error
  dryRun: false

rules:
  pr:
    - label: 'type: ✨ feat'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] ✨ New feature/m

    - label: 'type: 🐛 fix'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🐛 Bug fix/m

    - label: 'type: ♻️ refactor'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] ♻️ Refactoring/m

    - label: 'type: 🧪 test'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🧪 Test/m

    - label: 'type: 🎨 style'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🎨 Code/m

    - label: 'type: 🏗️ build'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🏗️ Build-related/m

    - label: 'type: ⚙️ ci'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] ⚙️ CI\/CD/m

    - label: 'type: 🧹 chore'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🧹 Chore/m

    - label: 'type: 📚 docs'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 📚 Documentation/m

    - label: 'type: 🚀 release'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] 🚀 Release/m

    - label: 'impact: 💥 breaking'
      skipIfBot: true
      matches:
        - operator: all
          conditions:
            - body: /^- \[(X|x)\] Breaking change$/m
