filters:
  # PULL_REQUEST_TEMPLATE.md
  - label: feat
    regexs:
      - /^- \[(X|x)\] New feature\b/m
    events: [pull_request]
    targets: [comment]
  - label: fix
    regexs:
      - /^- \[(X|x)\] Bug fix\b/m
    events: [pull_request]
    targets: [comment]
  - label: refactor
    regexs:
      - /^- \[(X|x)\] Refactoring\b/m
    events: [pull_request]
    targets: [comment]
  - label: test
    regexs:
      - /^- \[(X|x)\] Test\b/m
    events: [pull_request]
    targets: [comment]
  - label: style
    regexs:
      - /^- \[(X|x)\] Code style\b/m
    events: [pull_request]
    targets: [comment]
  - label: build
    regexs:
      - /^- \[(X|x)\] Build\b/m
    events: [pull_request]
    targets: [comment]
  - label: ci
    regexs:
      - /^- \[(X|x)\] CI\b/m
    events: [pull_request]
    targets: [comment]
  - label: chore
    regexs:
      - /^- \[(X|x)\] Chore\b/m
    events: [pull_request]
    targets: [comment]
  - label: docs
    regexs:
      - /^- \[(X|x)\] Documentation\b/m
    events: [pull_request]
    targets: [comment]
  - label: release
    regexs:
      - /^- \[(X|x)\] Release\b/m
    events: [pull_request]
    targets: [comment]

  - label: major
    regexs:
      - /Whether Breaking Changes(\s)*Does this PR contain breaking changes\?(\s)*- \[(X|x)\] Yes/i
    events: [pull_request]
    targets: [comment]
