# GitHub Labeler
# https://github.com/crazy-max/ghaction-github-labeler

# default
- name: "bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "#0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "#cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "#a2eeef"
  description: "New feature or request"
- name: "good first issue"
  color: "#7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "#008672"
  description: "Extra attention is needed"
- name: "invalid"
  color: "#e4e669"
  description: "This doesn't seem right"
- name: "question"
  color: "#d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "#ffffff"
  description: "This will not be worked on"

# custom - Priority
- name: "P0"
  color: "#ffebe9"
  description: "Priority: Urgent"
- name: "P1"
  color: "#fff8c5"
  description: "Priority: High"
- name: "P2"
  color: "#dafbe1"
  description: "Priority: Medium"
- name: "P3"
  color: "#ddf4ff"
  description: "Priority: Low"

# custom - Impact
- name: "impact: 💥 breaking"
  color: "#E99695"
  description: "Marks changes that break existing functionality."

# custom - Git convention
- name: "type: ✨ feat"
  color: "#28a745"
  description: "Git convention: feat"
- name: "type: 🐛 fix"
  color: "#d73a4a"
  description: "Git convention: fix"
- name: "type: ♻️ refactor"
  color: "#cfd3d7"
  description: "Git convention: refactor"
- name: "type: 🧪 test"
  color: "#bfdadc"
  description: "Git convention: test"
- name: "type: 🎨 style"
  color: "#e4e669"
  description: "Git convention: style"
- name: "type: 🏗️ build"
  color: "#f9d0c4"
  description: "Git convention: build"
- name: "type: ⚙️ ci"
  color: "#a2eeef"
  description: "Git convention: ci"
- name: "type: 🧹 chore"
  color: "#d4c5f9"
  description: "Git convention: chore"
- name: "type: 📚 docs"
  color: "#0075ca"
  description: "Git convention: docs"
- name: "type: 🚀 release"
  color: "#3C5085"
  description: "Git convention: release"

# custom - Semantic versioning
- name: "release: 💥 major"
  color: "#E99695"
  description: "Semantic versioning: major"
- name: "release: ✨ minor"
  color: "#F9D0C4"
  description: "Semantic versioning: minor"
- name: "release: 🛠️ patch"
  color: "#FEF2C0"
  description: "Semantic versioning: patch"

# custom - Semantic versioning(dependabot)
- name: "major"
  color: "#E99695"
  description: "Semantic versioning(Bot): major"
- name: "minor"
  color: "#F9D0C4"
  description: "Semantic versioning(Bot): minor"
- name: "patch"
  color: "#FEF2C0"
  description: "Semantic versioning(Bot): patch"
