name: Issue PR Labeler
description: |
  Automatically add labels by filtering the title and comment of issues and pull requests.
author: hoho4190
inputs:
  token:
    description: github token
    required: true
  disable-bot:
    description: |
      Whether to forbid filtering on issues and pull requests created by bots.
    required: false
    default: "true"
  config-file-name:
    description: |
      Configuration file name.
      This file should be located in `.github` path.
    required: false
    default: labeler-config.yml
runs:
  using: node20
  main: dist/index.js
branding:
  color: purple
  icon: tag
