name: 🏗️ Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Check format
        run: npm run format-check

      - name: Test
        run: npm test -- --coverage

      - name: Package
        run: npm run package

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Set environment variables
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for `gh api`
        # `gh api` → permissions: pull-requests: read
        run: |
          bash .github/scripts/build/set-env.sh

      - name: Set up Git user from pusher info
        if: ${{ env.IS_RELEASE_BRANCH_MERGE == 'true' }}
        run: |
          git config --global user.email ${{ github.event.pusher.email }}
          git config --global user.name ${{ github.event.pusher.name }}

      - name: Create and push new tag
        if: ${{ env.IS_RELEASE_BRANCH_MERGE == 'true' }}
        # `git push` → permissions: contents: write
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}
