# GitHub Labeler
# https://github.com/marketplace/actions/github-labeler

name: Github Labeler

on:
  push:
    branches:
      - main
    paths:
      - .github/github-labeler-config.yml
      - .github/workflows/github-labeler.yml

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Github Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/github-labeler-config.yml
          skip-delete: true
