name: PR event trigger
on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'main'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
