name: 'test'

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - locked
      - unlocked
      - ready_for_review
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Dump GITHUB context and event.json
        run: |
          echo "### 🔧 GITHUB ENVIRONMENT VARIABLES"
          for var in \
            GITHUB_ACTION \
            GITHUB_ACTION_PATH \
            GITHUB_ACTION_REPOSITORY \
            GITHUB_ACTIONS \
            GITHUB_ACTOR \
            GITHUB_ACTOR_ID \
            GITHUB_API_URL \
            GITHUB_BASE_REF \
            GITHUB_ENV \
            GITHUB_EVENT_NAME \
            GITHUB_EVENT_PATH \
            GITHUB_GRAPHQL_URL \
            GITHUB_HEAD_REF \
            GITHUB_JOB \
            GITHUB_OUTPUT \
            GITHUB_PATH \
            GITHUB_REF \
            GITHUB_REF_NAME \
            GITHUB_REF_PROTECTED \
            GITHUB_REF_TYPE \
            GITHUB_REPOSITORY \
            GITHUB_REPOSITORY_ID \
            GITHUB_REPOSITORY_OWNER \
            GITHUB_REPOSITORY_OWNER_ID \
            GITHUB_RETENTION_DAYS \
            GITHUB_RUN_ATTEMPT \
            GITHUB_RUN_ID \
            GITHUB_RUN_NUMBER \
            GITHUB_SERVER_URL \
            GITHUB_SHA \
            GITHUB_STEP_SUMMARY \
            GITHUB_TRIGGERING_ACTOR \
            GITHUB_WORKFLOW \
            GITHUB_WORKFLOW_REF \
            GITHUB_WORKFLOW_SHA \
            GITHUB_WORKSPACE
          do
            echo "$var=\"${!var}\""
          done

          echo ""
          echo "### 📄 EVENT.JSON CONTENTS"
          cat "$GITHUB_EVENT_PATH"
